export enum Role {
  ADMIN = 'ADMIN',
  DIRECTOR = 'DIRECTOR',
  MEMBER = 'MEMBER',
  RESPOSNABLE_MARCHE='RESPOSNABLE_MARCHE',
  RESPOSNABLE_AFFAIRES_FINANCIER='RESPOSNABLE_AFFAIRES_FINANCIER'
  // Add more roles as needed
}
